colors = {
    'PFGQ': 'red',
    'BootstrapPFGQ': 'maroon',
    'PFEnsembleTraces': 'pink',
    'PFGQ2': 'pink',
    'PFEnsemble': 'green',
    'PFEnsembleAverages': 'blue',
    'PFRobust': 'cyan',
    'GQ': 'blue',
    'QRC': 'orange',
    'QRC2': 'blue',
    'QC': 'green',
    'QC2': 'green',
    'QLearning': 'yellow',
}
